default[:apache][:conf_dir] 		= "/etc/apache2"
default[:apache][:sites_available] 	= "sites-available"
default[:apache][:sites_enabled] 	= "sites-enabled"
default[:apache][:default_conf] 	= "default.conf"
default[:apache][:balancing_conf] 	= "lb.conf"
